apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: mongo:4.0.4
        name: db
      restartPolicy: Always
