apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: stojan97/web
        ports:
        - containerPort: 5000
        env:
        - name: DB_PORT_27017_TCP_ADDR
          value: "127.0.0.1"
      restartPolicy: Always
