- hosts: master
  become: true
  become_user: ubuntu
  tasks:
    - name: set up db
      shell: kubectl apply -f ../deployments/db-deployment.yaml >> db.txt
      args:
        chdir: $HOME
        creates: db.txt

