- hosts: master
  become: true
  tasks:
    - name: Reset Kubernetes component
      shell: kubeadm reset --force
      register: reset_cluster
    
    - name: initialize the cluster
      when: reset_cluster is succeeded
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: init_cluster

    - name: create .kube directory
      become: true
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      when: init_cluster is succeeded
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: install Pod network
      when: init_cluster is succeeded
      become: true
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml
