- hosts: master
  become: true
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: worker
  become: true
  tasks:
    - name: Reset Kubernetes component
      shell: "kubeadm reset --force"
      register: reset_cluster

    - name: join cluster
      when: reset_cluster is succeeded
      shell: "{{ hostvars['master'].join_command }}"
